### PR TITLE
chore: upgrade React Native to 0.81 ⚛️🚀

### PR DESCRIPTION
**Pull request by theJian**
- Upgrade React Native 0.81
- New Architecture remains disabled

# Blocking issues

- [x] React 19 removed support for defaultProps on function components, need to find an alternative approach to `allowFontScaling: false` globally. 
  - #1489 
- [x] can potentially introduce conflicts with #1476 

- [x] sentry raised error: Debug ID was not found in the bundle. Call options.sentryBundleCallback if you are using a custom serializer. <https://github.com/getsentry/sentry-react-native/issues/5250>
- [x] `react-native-iap@12` compilation errors https://github.com/hyochan/react-native-iap/issues/2981

# Testing

- [x] Android build
- [x] iOS build
- [x] smoke test

### CODE REVIEW

File: apps/mobile/metro.config.js [hunk 1]
```diff
@@ -1,9 +1,7 @@
 const path = require('path');
 const fs = require('fs');
 const { getDefaultConfig, mergeConfig } = require('@react-native/metro-config');
-const {
-  createSentryMetroSerializer,
-} = require('@sentry/react-native/dist/js/tools/sentryMetroSerializer');
+const { withSentryConfig } = require('@sentry/react-native/metro');
```
Comment (richardo2016x) [inline apps/mobile/metro.config.js:4]: The changes here should be OK. I forgot why it was written this way before, but it seems to have been a change made in some attempt to handle custom sourcemap uploads in Sentry. However, this change is actually not much different from the default, so if it doesn't affect the packaging, it's fine to change it back to the default.

File: apps/mobile/index.js [hunk 2]
```diff
@@ -20,7 +20,7 @@ if (!__DEV__) {
 import './global';
 import './src/setup-app';
 if (__DEV__) {
-  import('./ReactotronConfig');
+  require('./ReactotronConfig');
```
Comment (richardo2016x) [inline apps/mobile/index.js]: I agree with claude bot. Is there a reason why `require` is necessary here? We don't want to block the original loading process here, so we originally used `import`.

File: .yarn/patches/@gorhom-bottom-sheet-npm-5.0.6-ee2c6d5dad.patch
Comment (richardo2016x) [inline .yarn/patches/@gorhom-bottom-sheet-npm-5.0.6-ee2c6d5dad.patch:1]: If the new version no longer causes the original type error, then deleting it here is fine.

File: apps/mobile/index.js (hunk 2 above)
Comment (theJian) [reply apps/mobile/index.js]: No, actually, this should later be reverted once Sentry's raising errors issue (mentioned in the pr decription) is resolved.

For some reason, Sentry complains about missing debug IDs for dynamically imported bundles.

File: apps/mobile/metro.config.js (hunk 1 above)
Comment (theJian) [reply apps/mobile/metro.config.js:4]: > I forgot why it was written this way before

I think it's the recommended way to integrate Sentry before, later Sentry starts to deprecate it and recommends using `withSentryConfig`.

Though I'm not so sure how it could affect bundling with hashcheck, you might want to take a look see if there's anything need to be updated accordingly.

File: apps/mobile/android/app/src/main/java/com/debank/rabbymobile/MainActivity.java [hunk 3]
```diff
@@ -1,22 +1,20 @@
...
-import android.os.Bundle;
-import org.devio.rn.splashscreen.SplashScreen; // react-native-splash-screen
+import org.devio.rn.splashscreen.SplashScreen;
 
 public class MainActivity extends ReactActivity {
+
   @Override
   protected void onCreate(Bundle savedInstanceState) {
-    // SplashScreen.show(this);
-    // https://github.com/crazycodeboy/react-native-splash-screen/blob/b47197626804a742b8569cad50d5e0ed92fc765c/android/src/main/java/org/devio/rn/splashscreen/SplashScreen.java#L25
```
Comment (richardo2016x) [inline apps/mobile/android/app/src/main/java/com/debank/rabbymobile/MainActivity.java:15]: Some comments are meaningful for understanding this part of the code later. These comments may even be explicitly stated as being included when the scaffolding was generated or in the relevant SDK documentation. Often, these comments explain why this part is handled in this way; do not delete them.

File: apps/mobile/android/app/build.gradle [hunk 4]
```diff
@@ -172,27 +168,10 @@ android {
 		  it.buildConfigField 'String', 'rabbitCode', "\"$System.env.RABBY_MOBILE_CODE\""
     }
     sourceSets {
-      main {
-        if (isNewArchitectureEnabled()) {
```
Comment (richardo2016x) [inline apps/mobile/android/app/build.gradle:176]: This section of code, which selects based on conditions, is necessary for future upgrades to newArch, and it is recommended not to delete it; otherwise, the code will have to be reorganized later.

**Comment by theJian** [comment]
@claude review this pr and produce a concise, execution-ready smoke test plan that covers ONLY the code paths and user flows impacted by this pr.

File: apps/mobile/src/components/customized/Switch.tsx [hunk 5]
```diff
@@ -2,27 +2,24 @@ import { useThemeColors } from '@/hooks/theme';
...
-        circleBorderWidth={1}
-        circleBorderActiveColor={colors['blue-default']}
-        circleBorderInactiveColor={colors['neutral-line']}
-        {...props}
-        ref={ref}
-      />
-    );
-  },
-);
+export const AppSwitch = (props: SwitchProps) => {
```
Comment (richardo2016x) [inline apps/mobile/src/components/customized/Switch.tsx:5]: Was this automatically changed by codex or cc? The modification here is not equivalent to the previous one, and settings should also depend on the ref attribute.

File: apps/mobile/src/components/customized/Switch2024.tsx [hunk 6]
```diff
@@ -2,29 +2,26 @@ import { useTheme2024 } from '@/hooks/theme';
 import React from 'react';
 import { RabbySwitch, SwitchProps } from '@/components/Switch/Switch';
 
-export const AppSwitch2024 = React.forwardRef<RabbySwitch, SwitchProps>(
-  (props, ref) => {
-    const { colors2024 } = useTheme2024();
+export const AppSwitch2024 = (props: SwitchProps) => {
```
Comment (richardo2016x) [inline apps/mobile/src/components/customized/Switch2024.tsx:5]: Like previous comment

File: apps/mobile/src/components/Switch/Switch.tsx [hunk 7]
```diff
@@ -46,213 +46,204 @@ export type SwitchProps = TouchableWithoutFeedbackProps & {
...
-    ] = React.useState({
-      value: propValue,
-      transformSwitch: new Animated.Value(
-        propValue ? circleSize / switchLeftPx : -circleSize / switchRightPx,
-      ),
-      backgroundColor: new Animated.Value(propValue ? 75 : -75),
-      circleColor: new Animated.Value(propValue ? 75 : -75),
-      circleBorderColor: new Animated.Value(propValue ? 75 : -75),
-    });
+const Switch = ({
```
Comment (richardo2016x) [inline apps/mobile/src/components/Switch/Switch.tsx:49]: Like comment above

**Review by richardo2016x — APPROVED** [review]

File: apps/mobile/android/app/build.gradle (hunk 4 above)
Comment (theJian) [reply apps/mobile/android/app/build.gradle:176]: sure, will revert in the following new arch related PR.
